export const MADI_AUTHENTICATION = Symbol('MADI_AUTHENTICATION');
export const MADI_SESSION_MANAGER = Symbol('MADI_SESSION_MANAGER');
export const MADI_AUTHENTICATED_CONVERSATION = Symbol('MADI_AUTHENTICATED_CONVERSATION');
