import { Controller, Get, Header } from '@nestjs/common';

@Controller('madi')
export class MadiVoiceUiController {
  @Get()
  @Header('Content-Type', 'text/html; charset=utf-8')
  render(): string {
    return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>M.A.D.I.</title><style>body{margin:0;min-height:100vh;background:#02050a;color:#e8f6ff;font:16px system-ui;display:grid;place-items:center;text-align:center}.app{width:min(1000px,94vw)}.stage{height:70vh;display:grid;place-items:center}.avatar{width:420px;height:500px;position:relative}.head{position:absolute;inset:6% 12% 16%;border:1px solid #9fe8ff;border-radius:48%;box-shadow:0 0 60px #1976b8,inset 0 0 50px #16486b}.eye{position:absolute;top:39%;width:18%;border-top:4px solid #9fe8ff;border-radius:50%}.eye.l{left:19%}.eye.r{right:19%}.brow{position:absolute;top:31%;width:20%;border-top:2px solid #9fe8ff}.brow.l{left:18%}.brow.r{right:18%}.nose{position:absolute;left:50%;top:43%;height:18%;border-left:1px solid #9fe8ff}.mouth{position:absolute;left:34%;top:67%;width:32%;height:9%;border-bottom:3px solid #9fe8ff;border-radius:0 0 50% 50%}.speaking .mouth{animation:talk .14s infinite alternate}.listening .eye{animation:blink 2s infinite}.thinking .eye{transform:scaleY(.6)}@keyframes talk{from{transform:scaleY(.4)}to{transform:scaleY(1.2)}}@keyframes blink{50%{transform:scaleY(.5)}}input,button{font:inherit;padding:12px;border-radius:10px;background:#07101c;color:#e8f6ff;border:1px solid #4ca6ff;margin:4px}.reply{min-height:35px}.hint{opacity:.6;font-size:12px}</style></head><body><main class="app"><h1>M.A.D.I.</h1><section class="stage"><div id="avatar" class="avatar listening"><div class="head"><div class="brow l"></div><div class="brow r"></div><div class="eye l"></div><div class="eye r"></div><div class="nose"></div><div class="mouth"></div></div></div></section><div id="status">Iniciando escucha…</div><div id="reply" class="reply">Estoy lista.</div><input id="text" placeholder="Escribe también aquí…"><button id="send">Enviar</button><button id="mic">🎙 Escucha automática</button><p class="hint">M.A.D.I. escucha automáticamente al abrir esta pantalla. Di “M.A.D.I.”, “Hola M.A.D.I.” o variantes naturales. Las acciones protegidas requieren confirmación explícita.</p></main><script>
const avatar=document.querySelector('#avatar'),status=document.querySelector('#status'),reply=document.querySelector('#reply'),text=document.querySelector('#text'),mic=document.querySelector('#mic');const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null,voiceListening=true,active=false,processing=false;let sessionId=localStorage.getItem('madi.anonymousSessionId')||crypto.randomUUID();localStorage.setItem('madi.anonymousSessionId',sessionId);let conversationId='';localStorage.removeItem('madi.conversationId');
function state(n,s){avatar.className='avatar '+n;status.textContent=s}
function norm(v){return v.normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').toLowerCase().replace(/[.,!?;:]/g,' ').replace(/\\s+/g,' ').trim()}
function wake(v){const n=norm(v);return /(^|\\s)m a d i(\\s|$)/.test(n)||/(^|\\s)madi(\\s|$)/.test(n)}
function strip(v){return norm(v).replace(/(^|\\s)m a d i(?=\\s|$)/,' ').replace(/(^|\\s)madi(?=\\s|$)/,' ').replace(/\\s+/g,' ').trim()}
function speak(v){if(!v||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(v);u.lang='es-AR';u.onstart=()=>state('speaking','Hablando…');u.onend=()=>state('listening',voiceListening?(active?'Escuchando a M.A.D.I.…':'Esperando “M.A.D.I.”…'):'Escucha detenida');speechSynthesis.speak(u)}
function extract(r){if(typeof r.responseText==='string'&&r.responseText.trim())return r.responseText;for(const k of ['conclusions','recommendations','proposedActions','data']){const v=r[k];if(Array.isArray(v)&&v.length){const x=v[0];if(typeof x==='string')return x;if(x&&typeof x==='object'){if(typeof x.text==='string')return x.text;if(typeof x.value==='string')return x.value}}}if(r.error&&r.error.message)return r.error.message;if(r.authorization&&r.authorization.reason)return r.authorization.reason;return r.status?'Estado: '+r.status:'Sin respuesta.'}
async function perform(content,token){const req={requestId:crypto.randomUUID(),timestamp:new Date().toISOString(),source:{applicationId:'madi-voice-ui',interface:'web'},input:{type:'text',content},metadata:{sessionId}};if(token)req.metadata.authorizationToken=token;const r=await fetch(token?'/interactions':'/madi/interaction',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(req)});if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
async function approve(content,d){const id=d.authorization&&d.authorization.approvalId;if(!id){reply.textContent='Esta acción requiere una autorización de sesión.';speak(reply.textContent);return false}const q='Necesito tu confirmación para realizar esta acción. ¿Quieres que continúe?';reply.textContent=q;speak(q);if(!window.confirm(q))return false;const r=await fetch('/madi/auth/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approvalId:id,sessionId})});const a=await r.json();if(!r.ok||!a.approved||!a.authorizationToken){reply.textContent='La autorización no pudo confirmarse.';return false}const result=await perform(content,a.authorizationToken);reply.textContent=extract(result);speak(reply.textContent);if(result.status==='completed'&&Array.isArray(result.execution)){const e=result.execution[result.execution.length-1],url=e&&e.result&&e.result.output&&e.result.output.openUrl;if(typeof url==='string')window.open(url,'_blank','noopener,noreferrer')}return true}
async function send(content){if(!content.trim()||processing)return;processing=true;state('thinking','Pensando…');try{const d=await perform(content);if(d.status==='needs_authorization'){await approve(content,d);return}reply.textContent=extract(d);speak(reply.textContent)}catch(e){reply.textContent='No pude completar la interacción: '+e.message;state('thinking','Error')}finally{processing=false}}
function startRecognition(){if(!recognition||!voiceListening)return;try{recognition.start();state('listening',active?'Escuchando a M.A.D.I.…':'Esperando “M.A.D.I.”…')}catch(e){if(e&&e.name!=='InvalidStateError')setTimeout(startRecognition,700)}}
document.querySelector('#send').onclick=()=>{send(text.value);text.value=''};text.addEventListener('keydown',e=>{if(e.key==='Enter'){send(text.value);text.value=''}});
if(Recognition){recognition=new Recognition();recognition.lang='es-AR';recognition.interimResults=false;recognition.continuous=true;recognition.onstart=()=>state('listening',active?'Escuchando a M.A.D.I.…':'Esperando “M.A.D.I.”…');recognition.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++){if(!e.results[i].isFinal)continue;const t=e.results[i][0].transcript.trim();if(!active){if(wake(t)){active=true;state('listening','Escuchando a M.A.D.I.…');const rest=strip(t);if(rest)send(rest)}}else{send(t)}}};recognition.onend=()=>{if(voiceListening)setTimeout(startRecognition,250)};recognition.onerror=e=>{if(e.error==='not-allowed'||e.error==='service-not-allowed'){voiceListening=false;reply.textContent='El navegador bloqueó el micrófono. Permite el acceso al micrófono para activar la escucha automática.';state('thinking','Micrófono no disponible')}else if(voiceListening){setTimeout(startRecognition,700)}};mic.onclick=()=>{voiceListening=!voiceListening;if(voiceListening){state('listening','Iniciando escucha…');startRecognition()}else{try{recognition.stop()}catch{}state('listening','Escucha detenida');mic.textContent='🎙 Activar voz'}};window.addEventListener('load',()=>setTimeout(startRecognition,300))}else{mic.disabled=true;status.textContent='Este navegador no admite reconocimiento de voz.'}
</script></body></html>`;
  }
}
