import { Controller, Get, Header } from '@nestjs/common';

/** Minimal browser voice interface. Browser STT/TTS are replaceable UI adapters; M.A.D.I. core remains unchanged. */
@Controller('madi')
export class MadiVoiceUiController {
  @Get()
  @Header('Content-Type', 'text/html; charset=utf-8')
  render(): string {
    return `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>M.A.D.I. — Interfaz de Voz</title>
<style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;background:#05070b;color:#dce8ff;font:16px system-ui,Segoe UI,sans-serif;display:grid;place-items:center}.app{width:min(900px,94vw);text-align:center}.orb{width:300px;height:300px;margin:20px auto;border-radius:50%;border:1px solid #4a79b8;box-shadow:0 0 35px #1e4d86,0 0 100px #102c50 inset;position:relative;display:grid;place-items:center;transition:.25s}.orb:before,.orb:after{content:"";position:absolute;border-radius:50%;border:1px solid #719fe0}.orb:before{width:78%;height:78%}.orb:after{width:58%;height:58%}.orb.speaking{animation:pulse .8s infinite alternate;box-shadow:0 0 55px #55a5ff,0 0 110px #102c50 inset}.orb.active{box-shadow:0 0 45px #4d8fd1,0 0 110px #102c50 inset}.face{width:130px;height:90px;position:relative;z-index:2}.eye{position:absolute;top:28px;width:25px;height:12px;border-top:3px solid #bfe1ff;border-radius:50%}.eye.l{left:15px}.eye.r{right:15px}.mouth{position:absolute;left:45px;top:55px;width:40px;height:12px;border-bottom:3px solid #bfe1ff;border-radius:50%}.status{opacity:.75;margin:8px}.reply{min-height:50px;margin:20px auto;max-width:700px}.controls{display:flex;gap:12px;justify-content:center;flex-wrap:wrap}button,input{font:inherit;border-radius:12px;border:1px solid #385b86;background:#0d1522;color:#e7f1ff;padding:12px 16px}button{cursor:pointer}button.primary{background:#17365d}.text{width:min(620px,80vw)}.hint{opacity:.5;font-size:13px}@keyframes pulse{to{transform:scale(1.035)}}
</style></head><body><main class="app"><h1>M.A.D.I.</h1><div id="orb" class="orb"><div class="face"><i class="eye l"></i><i class="eye r"></i><i class="mouth"></i></div></div><div id="status" class="status">En espera — di “M.A.D.I.”</div><div id="reply" class="reply">Estoy lista.</div><div class="controls"><input id="text" class="text" placeholder="Escribe también aquí…"><button id="send">Enviar</button><button id="mic" class="primary">🎙 Activar voz</button></div><p class="hint">Puedes decir “M.A.D.I.”, “Hola M.A.D.I.”, “Buen día M.A.D.I.” o cualquier saludo natural dirigido a M.A.D.I. La activación no autentica al usuario.</p></main>
<script>
const orb=document.querySelector('#orb'),status=document.querySelector('#status'),reply=document.querySelector('#reply'),text=document.querySelector('#text'),mic=document.querySelector('#mic');
const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition; let recognition=null; let active=false; let processing=false;
function state(s){status.textContent=s;orb.classList.toggle('speaking',s==='Hablando…');orb.classList.toggle('active',active)}
function normalize(value){return value.normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').toLowerCase().replace(/[.,!?;:]/g,' ').replace(/\\s+/g,' ').trim()}
function isWakePhrase(t){const n=normalize(t);return /(^|\\s)m a d i(\\s|$)/.test(n)||/(^|\\s)madi(\\s|$)/.test(n)}
function stripWakePhrase(t){return normalize(t).replace(/(^|\\s)m a d i(?=\\s|$)/,' ').replace(/(^|\\s)madi(?=\\s|$)/,' ').replace(/\\s+/g,' ').trim()}
function isWakeOnly(t){const n=stripWakePhrase(t);return !n||/^(hola|buenas|buen dia|buenas tardes|buenas noches)$/.test(n)}
function activate(){active=true;state('Escuchando a M.A.D.I.…');reply.textContent='Te escucho.'}
function standby(){active=false;processing=false;state('En espera — di “M.A.D.I.”')}
function speak(t){if(!('speechSynthesis' in window)||!t)return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(t);u.lang='es-AR';u.onstart=()=>state('Hablando…');u.onend=()=>{state(active?'Escuchando a M.A.D.I.…':'En espera — di “M.A.D.I.”');if(active&&recognition&&!processing)try{recognition.start()}catch{}};speechSynthesis.speak(u)}
function extract(r){for(const k of ['responseText','conclusions','recommendations','proposedActions','data']){const v=r[k];if(typeof v==='string'&&v.trim())return v;if(Array.isArray(v)&&v.length){const x=v[0];if(typeof x==='string')return x;if(x&&typeof x==='object'){if(typeof x.text==='string')return x.text;if(typeof x.value==='string')return x.value}}}if(r.error?.message)return r.error.message;if(r.authorization?.reason)return r.authorization.reason;return r.status?`Estado: ${r.status}`:'Sin respuesta.'}
async function send(content){if(!content.trim()||processing)return;processing=true;state('Pensando…');reply.textContent='';try{const r=await fetch('/interactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:crypto.randomUUID(),timestamp:new Date().toISOString(),source:{applicationId:'madi-voice-ui',interface:'web'},input:{type:'text',content}})});if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();const out=extract(data);reply.textContent=out;speak(out)}catch(e){reply.textContent='No pude completar la interacción: '+e.message;state('Error')}finally{processing=false}}
document.querySelector('#send').onclick=()=>send(text.value);text.addEventListener('keydown',e=>{if(e.key==='Enter')send(text.value)});
if(Recognition){recognition=new Recognition();recognition.lang='es-AR';recognition.interimResults=false;recognition.continuous=true;recognition.onstart=()=>state(active?'Escuchando a M.A.D.I.…':'En espera — di “M.A.D.I.”');recognition.onerror=e=>{if(e.error==='not-allowed'||e.error==='service-not-allowed'){state('Error');reply.textContent='El navegador no permitió usar el micrófono.'}};recognition.onend=()=>{if(active&&!processing)try{recognition.start()}catch{}};recognition.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++){if(!e.results[i].isFinal)continue;const t=e.results[i][0].transcript.trim();if(!active){if(isWakePhrase(t)){activate();const rest=stripWakePhrase(t);if(!isWakeOnly(t)&&rest)send(rest)}continue}text.value=t;send(t)}};mic.onclick=()=>{active=!active;if(active){activate();try{recognition.start()}catch{}}else{standby();try{recognition.stop()}catch{}}} }else{mic.disabled=true;reply.textContent='Este navegador no ofrece reconocimiento de voz.'}
</script></body></html>`;
  }
}
